# Generated by Django 5.2.5 on 2025-11-28 17:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='objectpermission',
            options={'verbose_name': 'Object Permission', 'verbose_name_plural': 'Object Permissions'},
        ),
        migrations.CreateModel(
            name='ModelPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('view', 'View'), ('delegate', 'Delegate')], max_length=10)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Model Permission',
                'verbose_name_plural': 'Model Permissions',
                'unique_together': {('user', 'action', 'content_type')},
            },
        ),
    ]
