# Generated by Django 5.2.5 on 2025-10-24 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript',
            field=models.TextField(blank=True, help_text='Optional transcript of the meeting', null=True),
        ),
    ]
