# Generated by Django 5.2.5 on 2025-10-24 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_meeting_end_time_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='start_date',
            field=models.DateField(blank=True, help_text='Optional start date', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.TimeField(blank=True, help_text='Optional start time', null=True),
        ),
    ]
