# Generated by Django 5.2.5 on 2025-10-24 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_meeting_start_date_alter_meeting_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='end_date',
            field=models.DateField(blank=True, help_text='Optional end date', null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.TimeField(blank=True, help_text='Optional end time', null=True),
        ),
    ]
