# Generated by Django 5.2.5 on 2025-10-24 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meeting_end_date_alter_meeting_end_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meeting',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='meeting',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
