# Generated by Django 5.2.5 on 2025-11-01 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_remove_meeting_end_date_remove_meeting_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
