# Generated by Django 5.2.5 on 2025-12-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0007_alter_meeting_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='transcript_gdrive_folder_id',
            field=models.CharField(blank=True, help_text='Google Drive folder ID containing meeting transcripts', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='transcript_gdrive_url',
            field=models.URLField(blank=True, help_text='Google Drive URL for meeting transcript', null=True),
        ),
        migrations.AddField(
            model_name='meeting',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL for this meeting', null=True),
        ),
    ]
