# Generated by Django 5.2.5 on 2025-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resolutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('resolutions', models.ManyToManyField(blank=True, help_text='resolutions required for this relationship', related_name='relationship_resolutions', to='resolutions.resolution')),
            ],
            options={
                'permissions': [('delegate_relationship', 'Can delegate relationship')],
            },
        ),
    ]
