# Generated by Django 5.2.5 on 2026-02-09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("relationships", "0003_relationship_proposals"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("communities", "0006_community_owners_admins"),
        ("projects", "0004_project_owners_admins"),
    ]

    operations = [
        migrations.RenameField(
            model_name="relationshipproposal",
            old_name="target_person",
            new_name="to_person",
        ),
        migrations.RenameField(
            model_name="relationshipproposal",
            old_name="target_community",
            new_name="to_community",
        ),
        migrations.RenameField(
            model_name="relationshipproposal",
            old_name="target_project",
            new_name="to_project",
        ),
        migrations.AddField(
            model_name="relationshipproposal",
            name="from_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationship_proposals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relationshipproposal",
            name="from_community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationship_proposals",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="relationshipproposal",
            name="from_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationship_proposals",
                to="projects.project",
            ),
        ),
        migrations.RenameField(
            model_name="relationshipinstance",
            old_name="target_person",
            new_name="to_person",
        ),
        migrations.RenameField(
            model_name="relationshipinstance",
            old_name="target_community",
            new_name="to_community",
        ),
        migrations.RenameField(
            model_name="relationshipinstance",
            old_name="target_project",
            new_name="to_project",
        ),
        migrations.AddField(
            model_name="relationshipinstance",
            name="from_person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationships",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="relationshipinstance",
            name="from_community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationship_instances",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="relationshipinstance",
            name="from_project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_relationship_instances",
                to="projects.project",
            ),
        ),
    ]
