# Generated by Django 5.2.5 on 2026-02-16 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0006_community_owners_admins'),
        ('projects', '0004_project_owners_admins'),
        ('relationships', '0004_relationship_from_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationshipinstance',
            name='to_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_relationship_instances', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='relationshipinstance',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_relationship_instances', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='relationshipproposal',
            name='to_community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_relationship_proposals', to='communities.community'),
        ),
        migrations.AlterField(
            model_name='relationshipproposal',
            name='to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_relationship_proposals', to='projects.project'),
        ),
    ]
