# Generated by Django 5.2.5 on 2026-02-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("relationships", "0005_alter_relationshipinstance_to_community_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="relationshipproposal",
            name="proposed_title",
        ),
        migrations.RemoveField(
            model_name="relationshipproposal",
            name="proposed_description",
        ),
    ]
