# Generated by Django 5.2.5 on 2025-12-13 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialroles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialrole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('socialrole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='socialroles.socialrole')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_socialrole_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('delegate_usersocialrole', 'Can delegate user social role')],
                'unique_together': {('user', 'socialrole')},
            },
        ),
    ]
