# Generated by Django 5.2.5 on 2026-02-01 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("capitals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("picture", models.ImageField(blank=True, help_text="Representative image for this location", null=True, upload_to="location_pictures/")),
                ("picture_thumbnail", models.ImageField(blank=True, editable=False, help_text="Automatically generated thumbnail", null=True, upload_to="location_pictures/thumbnails/")),
                ("view_members", models.BooleanField(default=False, help_text="Authenticated members can view this location.")),
                ("view_public", models.BooleanField(default=False, help_text="Public (unauthenticated) users can view this location.")),
                ("created_by", models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="locations", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "permissions": [("delegate_location", "Can delegate location")],
            },
        ),
        migrations.CreateModel(
            name="LocationCapital",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("capital", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_relationships", to="capitals.capital")),
                ("location", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="location_capital_relationships", to="locations.location")),
            ],
            options={
                "permissions": [("delegate_locationcapital", "Can delegate location capital")],
                "unique_together": {("location", "capital")},
            },
        ),
    ]
