# Generated by Django 5.2.5 on 2026-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bioregions", "0001_initial"),
        ("locations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="bioregions",
            field=models.ManyToManyField(blank=True, help_text="Bioregions this location is connected to", related_name="locations", to="bioregions.bioregion"),
        ),
    ]
