# Generated by Django 5.2.5 on 2025-12-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioregion',
            name='picture',
            field=models.ImageField(blank=True, help_text='Representative image for this bioregion', null=True, upload_to='bioregion_pictures/'),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Automatically generated thumbnail', null=True, upload_to='bioregion_pictures/thumbnails/'),
        ),
    ]
