# Generated by Django 5.2.5 on 2025-12-30 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0002_bioregion_picture_bioregion_picture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioregion',
            name='latitude',
            field=models.CharField(blank=True, help_text='Latitude coordinate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='location',
            field=models.CharField(blank=True, help_text='Location or address of this bioregion', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='longitude',
            field=models.CharField(blank=True, help_text='Longitude coordinate', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='radius_km',
            field=models.FloatField(blank=True, help_text='Radius of the bioregion in kilometers', null=True),
        ),
    ]
