# Generated by Django 5.2.5 on 2026-09-08 15:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0003_bioregion_latitude_bioregion_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bioregion',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text="Superadmin-assigned users who can manage this bioregion's permissions and settings", related_name='admin_bioregions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='view_members',
            field=models.BooleanField(default=False, help_text='Any authenticated member can view this bioregion. Users connected to the bioregion can always view it regardless of this setting.'),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='view_public',
            field=models.BooleanField(default=False, help_text='Public (unauthenticated) users can view this bioregion.'),
        ),
    ]
