# Generated by Django 5.2.5 on 2026-09-08 16:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0004_bioregion_admins_bioregion_view_members_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bioregion',
            name='members',
            field=models.ManyToManyField(blank=True, help_text='Users who are members of this bioregion', related_name='member_bioregions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bioregion',
            name='owners',
            field=models.ManyToManyField(blank=True, help_text="Superadmin-assigned users who can manage this bioregion's admins", related_name='owned_bioregions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bioregion',
            name='admins',
            field=models.ManyToManyField(blank=True, help_text="Users who can manage this bioregion's members and visibility settings", related_name='admin_bioregions', to=settings.AUTH_USER_MODEL),
        ),
    ]
