# Generated by Django 5.2.5 on 2026-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0005_bioregion_members_bioregion_owners_and_more'),
        ('commons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bioregion',
            name='visible_to_commons',
            field=models.ManyToManyField(blank=True, help_text='Members of these commons can view this bioregion, regardless of view_members/view_public.', related_name='visible_bioregions', to='commons.commons'),
        ),
    ]
