# Generated by Django 5.2.3 on 2025-06-24 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agreements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('agreements', models.ManyToManyField(blank=True, help_text='agreements required for this hat', related_name='hat_agreements', to='agreements.agreement')),
            ],
            options={
                'permissions': [('delegate_hat', 'Can delegate hat')],
            },
        ),
    ]
