# Generated by Django

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Capital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_path', models.CharField(blank=True, help_text="Relative path to static image (e.g. 'img/roles/weavers.webp')", max_length=255)),
            ],
            options={
                'permissions': [('delegate_capital', 'Can delegate capitals')],
            },
        ),
    ]
