# Generated by Django 5.2.5 on 2025-12-13 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maladaptives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMaladaptive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maladaptive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='maladaptives.maladaptive')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_maladaptive_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('delegate_usermaladaptive', 'Can delegate user maladaptive')],
                'unique_together': {('user', 'maladaptive')},
            },
        ),
    ]
