# Generated by Django 5.2.5 on 2025-10-20 13:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0001_initial'),
        ('challenges', '0001_initial'),
        ('metacrisis_facets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='level',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(-100), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='challenge',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='related_bioregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='bioregions.bioregion'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='related_facet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='metacrisis_facets.metacrisis_facet'),
        ),
    ]
