# Generated by Django 5.2.5 on 2025-12-06 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='picture',
            field=models.ImageField(blank=True, help_text='Representative image for this community', null=True, upload_to='community_pictures/'),
        ),
        migrations.AddField(
            model_name='community',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Automatically generated thumbnail', null=True, upload_to='community_pictures/thumbnails/'),
        ),
    ]
