# Generated by Django 5.2.5 on 2025-12-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0002_bioregion_picture_bioregion_picture_thumbnail'),
        ('communities', '0004_community_view_members_community_view_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='bioregions',
            field=models.ManyToManyField(blank=True, help_text='Bioregions this community is connected to', related_name='communities', to='bioregions.bioregion'),
        ),
    ]
