# Generated by Django 5.2.5 on 2026-02-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("communities", "0005_community_bioregions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="community",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can respond to relationship proposals for this community",
                related_name="owned_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="community",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can respond to relationship proposals for this community",
                related_name="admin_communities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
