# Generated by Django 5.2.5 on 2025-12-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='view_members',
            field=models.BooleanField(default=False, help_text='Authenticated members can view this project.'),
        ),
        migrations.AddField(
            model_name='project',
            name='view_public',
            field=models.BooleanField(default=False, help_text='Public (unauthenticated) users can view this project.'),
        ),
    ]
