# Generated by Django 5.2.5 on 2026-01-18 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0001_initial'),
        ('projects', '0002_project_view_members_project_view_public'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCapitalIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_in_relationships', to='capitals.capital')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_capital_in_relationships', to='projects.project')),
            ],
            options={
                'permissions': [('delegate_projectcapitalin', 'Can delegate project capital in')],
                'unique_together': {('project', 'capital')},
            },
        ),
        migrations.CreateModel(
            name='ProjectCapitalOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('capital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_out_relationships', to='capitals.capital')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_capital_out_relationships', to='projects.project')),
            ],
            options={
                'permissions': [('delegate_projectcapitalout', 'Can delegate project capital out')],
                'unique_together': {('project', 'capital')},
            },
        ),
    ]
