# Generated by Django 5.2.5 on 2026-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('capitals', '0001_initial'),
        ('projects', '0002_project_view_members_project_view_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='capitals_in',
            field=models.ManyToManyField(blank=True, help_text='Capitals that this project takes in or uses', related_name='projects_in', to='capitals.capital'),
        ),
        migrations.AddField(
            model_name='project',
            name='capitals_out',
            field=models.ManyToManyField(blank=True, help_text='Capitals that this project produces or outputs', related_name='projects_out', to='capitals.capital'),
        ),
    ]
