# Generated by Django 5.2.5 on 2026-02-09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_projectcapitalin_projectcapitalout"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="owners",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can respond to relationship proposals for this project",
                related_name="owned_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="project",
            name="admins",
            field=models.ManyToManyField(
                blank=True,
                help_text="Users who can respond to relationship proposals for this project",
                related_name="admin_projects",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
