# Generated by Django 5.2.5 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bioregions", "0003_bioregion_latitude_bioregion_location_and_more"),
        ("projects", "0004_project_owners_admins"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="bioregions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Bioregions this project is connected to",
                related_name="projects",
                to="bioregions.bioregion",
            ),
        ),
    ]
