# Generated by Django 5.2.5 on 2026-09-12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0011_project_visible_to_commons"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_orientation",
            field=models.BooleanField(default=False, help_text="This is the private orientation Move created for one player."),
        ),
        migrations.AddField(
            model_name="project",
            name="orientation_user",
            field=models.OneToOneField(blank=True, help_text="The player this orientation Move belongs to.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name="orientation_move", to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name="MoveStep",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("requires_review", models.BooleanField(default=False, help_text="Ask a move owner to review completion when the player is not an owner.")),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_by", models.ManyToManyField(blank=True, related_name="completed_move_steps", to=settings.AUTH_USER_MODEL)),
                ("project", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="steps", to="projects.project")),
                ("reviewed_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reviewed_move_steps", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["order", "id"],
                "indexes": [models.Index(fields=["project", "order"], name="projects_mo_project_b8f8da_idx")],
            },
        ),
    ]
