# Generated by Django 5.2.5 on 2025-12-06 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('text_content', models.TextField(blank=True, help_text='The main narrative content of the story')),
                ('view_members', models.BooleanField(default=False, help_text='Authenticated members can view this story.')),
                ('view_public', models.BooleanField(default=False, help_text='Public (unauthenticated) users can view this story.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authored_stories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'stories',
                'ordering': ['-created_at'],
                'permissions': [('delegate_story', 'Can delegate story')],
            },
        ),
        migrations.CreateModel(
            name='StoryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('video_url', 'Video URL')], max_length=20)),
                ('file', models.FileField(blank=True, help_text='Image or video file', null=True, upload_to='story_media/')),
                ('file_thumbnail', models.ImageField(blank=True, editable=False, help_text='Automatically generated thumbnail for images', null=True, upload_to='story_media/thumbnails/')),
                ('url', models.URLField(blank=True, help_text='URL for embedded videos (YouTube, Vimeo, etc.)', null=True)),
                ('caption', models.TextField(blank=True, help_text='Caption or description for this media')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='stories.story')),
            ],
            options={
                'verbose_name_plural': 'story media',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='StoryAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('attachment_context', models.CharField(blank=True, help_text="Context for why this story relates (e.g., 'learning_journey', 'breakthrough_moment')", max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='stories.story')),
            ],
            options={
                'ordering': ['created_at'],
                'unique_together': {('story', 'content_type', 'object_id')},
            },
        ),
    ]
