# Generated by Django 5.2.5 on 2025-12-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storymedia',
            name='file',
            field=models.ImageField(blank=True, help_text='Image file', null=True, upload_to='story_media/'),
        ),
        migrations.AlterField(
            model_name='storymedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video_url', 'Video URL')], max_length=20),
        ),
    ]
