# Generated by Django 5.2.5 on 2026-01-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_alter_storymedia_file_alter_storymedia_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='YouTube video URL to embed (e.g., https://www.youtube.com/watch?v=...)', null=True),
        ),
    ]
