# Generated by Django 5.2.5 on 2026-09-08 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bioregions', '0005_bioregion_members_bioregion_owners_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('agreements_url', models.URLField(blank=True, help_text='Link to a Google Doc specifying the rights and responsibilities of commons membership.', null=True)),
                ('view_members', models.BooleanField(default=False, help_text='Any authenticated member can view this commons.')),
                ('view_public', models.BooleanField(default=False, help_text='Public (unauthenticated) users can view this commons.')),
                ('admins', models.ManyToManyField(blank=True, help_text="Users who can manage this commons' members, applications and invites.", related_name='admin_commons', to=settings.AUTH_USER_MODEL)),
                ('bioregion', models.ForeignKey(blank=True, help_text='Bioregion this commons is usually linked to. Leave blank for a non-regional commons.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons', to='bioregions.bioregion')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, help_text='Users who are members of this commons.', related_name='member_commons', to=settings.AUTH_USER_MODEL)),
                ('owners', models.ManyToManyField(blank=True, help_text="Superadmin-assigned users who can manage this commons' admins.", related_name='owned_commons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'commons',
                'permissions': [('delegate_commons', 'Can delegate commons')],
            },
        ),
        migrations.CreateModel(
            name='CommonsApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(blank=True, help_text='Optional note from the applicant.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=16)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_applications', to=settings.AUTH_USER_MODEL)),
                ('commons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='commons.commons')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_applications_decided', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('commons', 'applicant'), name='unique_pending_commons_application')],
            },
        ),
        migrations.CreateModel(
            name='CommonsInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('revoked', 'Revoked')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('commons', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='commons.commons')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commons_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('invited_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commons_invites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('commons', 'invited_user'), name='unique_pending_commons_invite')],
            },
        ),
    ]
