from django.core.management.base import BaseCommand
from ...models import Metacrisis_facet


class Command(BaseCommand):
    help = "Seeds the database with initial metacrisis facet data"

    def handle(self, *args, **options):
        self.stdout.write("Seeding metacrisis facets...")

        metacrisis_facet_templates = [
            {"title": "Extinction Edge", "description": "These are threats that could lead to human extinction or permanently curtail humanity's potential. Examples include nuclear war, unchecked artificial intelligence, and catastrophic climate change. The existential risks are amplified by the interconnections between technology, environment, and global politics.", "image_path": "img/metacrisis_facets/1_ExtinctionEdge.png"},
            {"title": "Fragile Web", "description": "This facet involves the inherent vulnerabilities in our global systems—economic, political, environmental, and technological. As these systems become more interconnected, they also become more susceptible to cascading failures, where a disruption in one area can trigger a chain reaction of crises across multiple domains.", "image_path": "img/metacrisis_facets/2_FragileWeb.png"},
            {"title": "Truth Tornado", "description": "This refers to the breakdown of shared understanding and trust in knowledge systems. Misinformation, disinformation, the erosion of expertise, and the polarization of discourse contribute to this crisis, making it difficult for societies to agree on facts or to make collective decisions.", "image_path": "img/metacrisis_facets/3_TruthTornado.png"},
            {"title": "Soul Split", "description": "This facet involves the fragmentation of cultural narratives and identities, leading to a loss of meaning, purpose, and connection among individuals and communities. The increase in mental health issues, social isolation, and the decline of community bonds are in part symptomatic of this broader cultural and psychological unraveling.", "image_path": "img/metacrisis_facets/4_SoulSplit.png"},
            {"title": "Earth Erosion", "description": "The ecological aspect of the metacrisis includes environmental degradation, biodiversity loss, and climate change. These issues destabilize the natural systems upon which all life depends. The ecological crisis is exacerbated by human activities that disrupt the planet's ecosystems at a global scale.", "image_path": "img/metacrisis_facets/5_EarthErosion.png"},
            {"title": "Power Pyramid", "description": "Growing inequality, both within and between countries, is another critical element of the metacrisis. The concentration of wealth and power in the hands of a few, coupled with the disenfranchisement of large populations, fuels social unrest, destabilizes political systems, and hinders collective action to address global challenges.", "image_path": "img/metacrisis_facets/6_PowerPyramid.png"},
            {"title": "Tech Tsunami", "description": "Advances in technology, particularly in artificial intelligence, biotechnology, and digital surveillance, pose both opportunities and risks. The rapid pace of technological change outstrips the capacity of social, legal, and ethical systems to keep up, leading to unintended consequences and new forms of control and exploitation.", "image_path": "img/metacrisis_facets/7_TechTsunami.png"},
            {"title": "Leadership Lapse", "description": "Many of the world's governance systems are not equipped to handle the complexity of the metacrisis. These systems often operate in silos, are slow to adapt, and are prone to corruption, inefficiency, and short-term thinking. This governance deficit makes it difficult to coordinate global responses to interconnected crises.", "image_path": "img/metacrisis_facets/8_LeadershipLapse.png"},
            {"title": "Resilient Renaissance", "description": "Humanity’s future is safeguarded by robust, adaptive systems capable of absorbing shocks from technological advancements, environmental changes, and political tensions. Through collaboration across science, ethics, and governance, we create frameworks for responsible innovation, sustainable ecosystems, and peace-building, ensuring long-term human flourishing and the full realization of our potential.", "image_path": "img/metacrisis_facets/1A_ResilientRenaissance.png"},
            {"title": "Interwoven Harmony", "description": "A resilient global network of systems—economic, political, environmental, and technological—where interdependencies foster cooperation, mutual support, and adaptability. This harmonious interconnection creates a world where local disruptions are mitigated, and cascading failures are prevented by strong, decentralized solutions and proactive, agile governance.", "image_path": "img/metacrisis_facets/2A_InterwovenHarmony.png"},
            {"title": "Shared Light", "description": "A deeply interconnected and trustworthy knowledge ecosystem that transcends ideological divides and fosters collective wisdom. Through a culture of open inquiry, shared learning, and diverse yet respectful discourse, societies cultivate a shared understanding rooted in transparency, verified knowledge, and mutual respect. Communities can agree on facts and engage in productive debate, leading to informed, collective decision-making.", "image_path": "img/metacrisis_facets/3A_SharedLight.png"},
            {"title": "Cultural Wholeness", "description": "A flourishing of diverse, inclusive cultural narratives that inspire purpose, meaning, and connection across individuals and communities. Reunited with a sense of belonging and shared values, people form strong bonds of community, while embracing both global perspectives and local traditions. A deep sense of psychological well-being and cultural continuity fosters resilience in the face of personal and collective challenges.", "image_path": "img/metacrisis_facets/4A_CulturalWholeness.png"},
            {"title": "Regenerative Abundance", "description": "Human activity is in harmony with the Earth’s natural systems, fostering ecosystems that not only sustain but regenerate life. Biodiversity thrives, climate change is mitigated through equitable, ecological practices, and humanity becomes stewards of a flourishing planet. Regenerative agriculture, circular economies, and localized ecological governance ensure that nature and society flourish together.", "image_path": "img/metacrisis_facets/5A_RegenerativeAbundance.png"},
            {"title": "Equitable Commons", "description": "A just and equitable global system where power and resources are distributed in a way that fosters opportunity, fairness, and dignity for all. Communities practice economic, social, and political inclusivity, and policies are designed to diminish inequalities while empowering disenfranchised populations. Cooperative governance and shared wealth systems ensure that all have a voice and stake in our collective future.", "image_path": "img/metacrisis_facets/6A_EquitableCommons.png"},
            {"title": "Tech Symphony", "description": "A balanced and humane integration of technology into society, where AI, biotechnology, and digital innovations are designed and governed for the benefit of all. Technology enhances human potential while being guided by ethical principles, safeguarding privacy, and amplifying human agency. Innovations in health, education, and the environment serve the common good, promoting wellbeing, creativity, and autonomy.", "image_path": "img/metacrisis_facets/7A_TechSymphony.png"},
            {"title": "Adaptive Stewardship", "description": "Dynamic, agile leadership systems rooted in wisdom, foresight, and long-term thinking guide global and local responses to challenges. Governance is transparent, responsive, and adaptive, with diverse leadership structures that prioritize collaboration and shared responsibility. Leaders act as stewards of complexity, working across silos and engaging citizens in a co-creative process to shape a thriving, interconnected world.", "image_path": "img/metacrisis_facets/8A_AdaptiveStewardship.png"},

        ]
        for template in metacrisis_facet_templates:
            obj, created = Metacrisis_facet.objects.get_or_create(
                title=template["title"],
                defaults={
                    "description": template["description"],
                    "image_path": template["image_path"]
                },
            )
            if created:
                self.stdout.write(self.style.SUCCESS(f"Created: {obj.title}"))
            else:
                self.stdout.write(self.style.WARNING(f"Skipped (already exists): {obj.title}"))

        self.stdout.write(self.style.SUCCESS("✅ Done seeding metacrisis facets."))
