# Generated by Django 5.2.5 on 2025-11-02 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bioregions', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_bioregions',
            field=models.ManyToManyField(blank=True, related_name='users', to='bioregions.bioregion'),
        ),
    ]
