# Generated by Django 5.2.5 on 2025-11-07 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_user_bioregions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='view_members',
            field=models.BooleanField(default=False, help_text='Indicates if the user can view members.'),
        ),
        migrations.AddField(
            model_name='user',
            name='view_public',
            field=models.BooleanField(default=False, help_text='Indicates if the user can view public content.'),
        ),
    ]
