# Generated by Django 5.2.5 on 2025-11-08 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacrisis_facets', '0001_initial'),
        ('users', '0003_user_view_members_user_view_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_metacrisis_facets',
            field=models.ManyToManyField(blank=True, related_name='users', to='metacrisis_facets.metacrisis_facet'),
        ),
    ]
