# Generated by Django 5.2.5 on 2025-12-06 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_user_metacrisis_facets'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to='user_pictures/'),
        ),
        migrations.AddField(
            model_name='user',
            name='picture_thumbnail',
            field=models.ImageField(blank=True, editable=False, help_text='Automatically generated thumbnail', null=True, upload_to='user_pictures/thumbnails/'),
        ),
    ]
