# Generated by Django 5.2.5 on 2025-12-06 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_picture_user_picture_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, help_text='User biography or description'),
        ),
    ]
