# Generated by Django 5.2.5 on 2025-12-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maladaptives', '0002_usermaladaptive'),
        ('metacrisis_facets', '0002_usermetacrisisfacet'),
        ('socialroles', '0002_usersocialrole'),
        ('users', '0007_user_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_maladaptives',
            field=models.ManyToManyField(blank=True, related_name='users', through='maladaptives.UserMaladaptive', to='maladaptives.maladaptive'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_metacrisis_facets',
            field=models.ManyToManyField(blank=True, related_name='users', through='metacrisis_facets.UserMetacrisisFacet', to='metacrisis_facets.metacrisis_facet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_socialroles',
            field=models.ManyToManyField(blank=True, related_name='users', through='socialroles.UserSocialrole', to='socialroles.socialrole'),
        ),
    ]
