# Generated by Django 5.2.5 on 2025-12-13 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_user_maladaptives_and_more'),
        ('users', '0008_transition_to_through_models'),
    ]

    operations = [
    ]
