# Generated by Django 5.2.5 on 2025-12-17 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_merge_20251213_1939'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGoogleAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField(help_text='Encrypted Google OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted Google OAuth refresh token', null=True)),
                ('token_expiry', models.DateTimeField(blank=True, help_text='When the access token expires', null=True)),
                ('scopes', models.TextField(help_text='Space-separated list of granted OAuth scopes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_auth', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Google Authentication',
                'verbose_name_plural': 'User Google Authentications',
            },
        ),
    ]
