# Generated by Django 5.2.5 on 2026-02-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_usergoogleauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['full_name']},
        ),
    ]
