# Generated by Django 5.2.5 on 2026-02-16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_project_bioregions"),
        ("users", "0011_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_projects",
            field=models.ManyToManyField(
                blank=True, related_name="connected_users", to="projects.project"
            ),
        ),
    ]
