# Generated by Django 5.2.5 on 2026-02-18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_user_user_projects"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="ai_transcript_processing",
            field=models.BooleanField(
                default=False,
                help_text="Allow AI (like GPT in temporary mode) to analyze meeting transcripts to make connections between people and extract useful tasks.",
            ),
        ),
    ]
