# Generated by Django 5.2.5 on 2026-09-08 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('users', '0016_user_alternate_deck'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='visible_to_commons',
            field=models.ManyToManyField(blank=True, help_text="Members of these commons can view this person's profile, regardless of view_members/view_public.", related_name='visible_people', to='commons.commons'),
        ),
    ]
