# Generated by Django 5.2.5 on 2026-09-08 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commons', '0001_initial'),
        ('users', '0017_user_visible_to_commons'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinvite',
            name='requested_commons',
            field=models.ManyToManyField(blank=True, help_text='Commons the invited person will automatically apply to join upon registration.', related_name='signup_invites', to='commons.commons'),
        ),
    ]
