# Generated by Django 5.2.5 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0019_onboarding_and_requests"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="onboarding_completed_sections",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
