# Generated by Django 5.2.5 on 2025-12-13 17:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metacrisis_facets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMetacrisisFacet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('metacrisis_facet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_relationships', to='metacrisis_facets.metacrisis_facet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_metacrisis_facet_relationships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('delegate_usermetacrisisfacet', 'Can delegate user metacrisis facet')],
                'unique_together': {('user', 'metacrisis_facet')},
            },
        ),
    ]
